name: Build Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npx electron-builder build --win --publish never --config electron-builder.mjs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: PD2MM-windows
          path: dist/PD2MM-*.exe*
